name: Deploy (Remote Build via SSH)

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Safety check: fail early if secrets are missing (without printing them)
      - name: Validate required secrets
        run: |
          : "${{ secrets.DEPLOY_HOST?DEPLOY_HOST secret is missing }}"
          : "${{ secrets.DEPLOY_USER?DEPLOY_USER secret is missing }}"
          : "${{ secrets.DEPLOY_SSH_KEY?DEPLOY_SSH_KEY secret is missing }}"

      - name: Build on server & reload Nginx
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          script_stop: true
          script: |
            set -euo pipefail
            APP_DIR="/home/web3sec/Web3-Security-Summit-Africa"
            WEB_ROOT="$APP_DIR/dist"

            if ! command -v git >/dev/null; then
              sudo apt-get update -y
              sudo apt-get install -y git curl ca-certificates
            fi

            # Ensure Node 20
            if ! command -v node >/dev/null || [ "$(node -v | sed 's/v\([0-9]*\).*/\1/')" -lt 18 ]; then
              curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
              sudo apt-get install -y nodejs
            fi

            # Clone once; pull on subsequent runs
            if [ ! -d "$APP_DIR/.git" ]; then
              git clone https://github.com/GuildAudits/Web3-Security-Summit-Africa.git "$APP_DIR"
            fi
            cd "$APP_DIR"
            git fetch origin
            git checkout main
            git reset --hard origin/main

            npm ci
            npm run build

            sudo chmod 755 /home /home/web3sec "$APP_DIR" "$WEB_ROOT"
            sudo find "$WEB_ROOT" -type d -exec chmod 755 {} \;
            sudo find "$WEB_ROOT" -type f -exec chmod 644 {} \;
            sudo chown -R web3sec:www-data "$APP_DIR"

            sudo nginx -t
            sudo systemctl reload nginx

            # quick health check
            curl -sfI http://localhost >/dev/null
